/** In-memory catalog when PostgreSQL is unavailable (local demo without Docker). */
export const fallbackCatalog = [
  {
    id: "dest-jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    country: "India",
    description:
      "The Pink City blends Rajput grandeur, bustling bazaars, and desert-edge adventures.",
    vibe: "heritage",
    budgetLevel: "moderate",
    tags: ["forts", "crafts", "royal", "street food"],
    heroImage: "/images/jaipur.jpg",
    location: "Rajasthan, India",
    attractions: [
      {
        id: "att-amber",
        name: "Amber Fort",
        description: "Hilltop fort with mirrored halls and elephant paths.",
        category: "heritage",
        hiddenGem: false,
        tags: ["fort", "architecture"],
      },
      {
        id: "att-stepwell",
        name: "Panna Meena ka Kund",
        description: "Symmetrical stepwell locals still use for quiet morning walks.",
        category: "heritage",
        hiddenGem: true,
        tags: ["stepwell", "photography"],
      },
      {
        id: "att-blue-pottery",
        name: "Blue Pottery Lane, Kot Jewar",
        description: "Family workshops where artisans hand-paint turquoise ceramics.",
        category: "craft",
        hiddenGem: true,
        tags: ["artisan", "workshop"],
      },
    ],
  },
  {
    id: "dest-munnar",
    name: "Munnar",
    state: "Kerala",
    country: "India",
    description: "Mist-wrapped tea estates, silent valleys, and spice-scented air.",
    vibe: "nature",
    budgetLevel: "moderate",
    tags: ["tea", "hiking", "wildlife"],
    heroImage: "/images/munnar.jpg",
    location: "Western Ghats, Kerala",
    attractions: [
      {
        id: "att-tea-trail",
        name: "Kolukkumalai Tea Trail",
        description: "World's highest tea plantation trek with sunrise views.",
        category: "nature",
        hiddenGem: true,
        tags: ["trek", "tea"],
      },
      {
        id: "att-spice",
        name: "Lockhart Gap Spice Grove",
        description: "Small organic spice garden with tasting sessions.",
        category: "food",
        hiddenGem: true,
        tags: ["spice", "farm"],
      },
    ],
  },
  {
    id: "dest-varanasi",
    name: "Varanasi",
    state: "Uttar Pradesh",
    country: "India",
    description: "Ancient ghats, river rituals, and labyrinthine alleys of faith.",
    vibe: "spiritual",
    budgetLevel: "budget",
    tags: ["ghats", "ganga", "temples"],
    heroImage: "/images/varanasi.jpg",
    location: "Uttar Pradesh, India",
    attractions: [
      {
        id: "att-assi",
        name: "Assi Ghat Dawn Walk",
        description: "Quiet southern ghat where locals practice yoga at sunrise.",
        category: "spiritual",
        hiddenGem: true,
        tags: ["ghat", "sunrise"],
      },
      {
        id: "att-silk",
        name: "Lallapura Silk Weavers' Courtyard",
        description: "Generations of Banarasi weavers working on handlooms.",
        category: "craft",
        hiddenGem: true,
        tags: ["textile", "artisan"],
      },
    ],
  },
] as const;
